## do lokalnego testowania
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "3000:3000"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "5173:80"
    environment:
      VITE_API_URL: http://localhost:3000/
      BACKEND_HOST: localhost:3000/
    depends_on:
      - backend