# Budowa backendu
FROM node:20-bookworm AS backend
WORKDIR /app

COPY backend/package*.json ./

RUN npm ci --omit=dev

COPY backend/ .

ENV NODE_ENV=production

EXPOSE 3000
CMD ["node", "server.js"]