# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - projekt-zaliczeniowy-tc

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm install

      - name: Build frontend
        working-directory: ./frontend
        run: npm run build

      - name: Install backend dependencies
        working-directory: ./backend
        run: npm install

      - name: Copy frontend build into backend/public
        run: |
          rm -rf ./backend/public
          mkdir -p ./backend/public
          cp -r ./frontend/dist/* ./backend/public/

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_9B8C3FBDD77F4B03A03161A69BE785F9 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_CB5D737213554238BDB288BBA04FAD2D }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_A467FAC0E7804D0A965EC2F126C000A5 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'projekt-zaliczeniowy-tc'
          slot-name: 'Production'
          package: ./backend
          
